### ISSUE TITLE
'P2PKit/P2PKit.h' file not found

### ISSUE THREAD

**Issue by gimwee** [Uepaa-AG/react-native-p2pkit#15]
try to install p2pkit but get 'P2PKit/P2PKit.h' file not found error

**Comment by kanso-michael** [comment]
I am only having this issue on verion `1.6.1` of cocoapods, reverting back to using `1.5.2` fixes the issue for me for now. Hope this helps you @gimwee.

**Comment by gimwee** [comment]
we end up have to move p2pkit code to our own library :\
