### ISSUE TITLE
Please enable p2pkit first before calling any other method on it!

### ISSUE THREAD

**Issue by FredyC** [Uepaa-AG/react-native-p2pkit#7]
This is probably an issue in P2P kit SDK itself. I am getting this error on Android in somewhat random manner, mostly after reloading the app. After the full restart, it works again, until the first reload.

I am directly calling `PPKReactBridge.enable('XXX')` as I want to handle callbacks a bit differently than with the class in this package.

I should also note that I am using Genymotion emulator, which might be the reason why it calls disable (see the screenshot) on its own. However, it's not the desired behavior.

I think that the SDK should not try to be so invasive. It's impossible to catch native code exceptions in JS, isn’t it? Instead of throwing an error and crashing the app, I would rather it sits there silently and not work until I call enable.

![image](https://user-images.githubusercontent.com/1096340/40278221-8ac000a0-5c2d-11e8-8fb6-0ff5ecb7c853.png)

**Comment by FredyC** [comment]
Thank you, looks like the PR has indeed fixed this issue. Never thought it would so simple fix :) Hopefully, someone can merge it soon. 

/cc @Schlaepfer

**Comment by Schlaepfer** [comment]
Hey chrise86, thanks a lot for the PR, I merged the changes into master.

**Comment by FredyC** [comment]
@Schlaepfer I am wondering why there is no version release and it's necessary to install from the repo? It's rather an unusual approach.
